### ISSUE TITLE
Feedback: Unsuitability for Longitudanal Studies

### ISSUE THREAD

**Issue by kchawla-pi** [INCF/BIDS#29] opened 2018-09-26 11:24 UTC
@chrisfilo I collected some feedback regarding BIDS. I am posting it here near verbatim:

Oh.  I just remembered my biggest problem with BIDS.
BIDS and the BIDS validator work great for single session studies or completed studies.  I am having major issues using it for longitudinal studies.
If you use it for single session studies then you can run the bids validator after you add a scan.  This works great. You can see if you are missing any data or if there are problems with your protocol that doesn’t match the other scans.
If you do the same thing for a longitudinal study then the as soon as you scan the the second session the other subjects that have a single session will be reported as missing the second session.  The output can be very extensive and hide valuable information from the second scan.
I haven’t found a good way of dealing with this. I have modified the .bidsignore file to ignore the first session scans (or a portion of them) but I also have to modify the participant.list
This is straightforward to do but I have made mistakes and have had to go back and recreate the file.
It would be nice to have a flag in the bids validator to ignore sessions that have not been acquired yet from the output.

Additional Feedback:

We use the heudiconv converter.  It works great and puts things into BIDS format.
My biggest complaint is the data structure is fine but there are many missing modalities that are still missing (Arterial Spin Labeling, Susceptibility Weighted Imaging, and Magnetization transfer).  ASL and SWI have been proposed as enhancements but have not been accepted yet. This is a minor inconvenience. I use the .bidsignore file to eliminate these from the bids validation.

**Comment by chrisfilo** [comment] 2018-09-26 15:45
Thanks for your feedback. This is a duplicate of https://github.com/INCF/bids-validator/issues/135

**Closed by chrisfilo** 2018-09-26 15:45 UTC
